File added and canceled events
darkroom-com/dropzone_input pull request #10
Opened 2021-02-03 21:32 UTC by robchia

- Added `file-added-event`, `file-canceled-event`
- Expose `cancel` method to abort file

2021-02-03 22:06 UTC, tobyond approved these changes
👍 
did the stimulus 2 update ever get integrated? I'm still seeing the error in console.

2021-02-04 13:27 UTC, trobrock requested changes

2021-02-04 13:27 UTC, trobrock commented on CHANGELOG.md
> +## [1.0.2] - 2021-02-03
Should be 1.1.0, minor updates are reserved for bugs. https://semver.org/

2021-02-04 13:27 UTC, trobrock commented on src/index.js
> +      }, 3500);
What is the delay for?

2021-02-04 16:48 UTC, robchia commented on src/index.js
> +      }, 3500);
I don't quite remember-- removing it

2021-02-04 16:59 UTC, robchia commented
@tobyond Yeah that should've been updated, it's correct in dev, but not sure why it's still rendering the old "data-target" in prod

2021-02-04 19:04 UTC, trobrock approved these changes

2021-02-05 18:25 UTC, merged