Update Stimulus to 2.0.0
darkroom-com/dropzone_input pull request #9
Opened 2021-01-12 20:51 UTC by robchia

2021-01-12 21:26 UTC, tobyond approved these changes
sweet!

2021-01-13 13:54 UTC, trobrock requested changes

2021-01-13 13:54 UTC, trobrock commented on CHANGELOG.md
> +## [0.0.6] - 2021-01-12
Mind making this `1.0.0`?

2021-01-13 17:43 UTC, trobrock approved these changes

2021-01-13 19:52 UTC, merged